import { useState } from 'react';
import { CopyBlock, Navigation, Wordmark } from './app';

type Command = { name: string; status: 'Available' | 'Planned'; mutates: string; description: string; example: string };
const commands: Command[] = [
  ['/art-direct','Available','After approval','Runs discovery, approval, direction selection, Design Plan v2, implementation, and review for a new or substantially redesigned interface.','/art-direct Create an editorial landing page for a developer tool.'],
  ['/audit','Available','No','Produces a prioritized, evidence-led design and implementation audit of an existing route or component.','/audit frontend/src at desktop and mobile widths.'],
  ['/polish','Available','Yes','Applies bounded improvements to hierarchy, typography, spacing, responsiveness, and accessibility without redesigning behavior.','/polish Tighten the installation page typography and mobile spacing.'],
  ['/cleanup','Available','Yes','Removes verified redundant, inconsistent, obsolete, or generic UI patterns while preserving behavior and public APIs.','/cleanup Consolidate duplicated tokens in frontend/src/styles.css.'],
  ['/review-ui','Available','No','Coordinates multiple design-review perspectives into one deduplicated, ranked report and repair sequence.','/review-ui Review the installation page against the selected direction.'],
  ['/animate','Planned','Yes','Adds purposeful transitions, micro-interactions, scroll effects, loading feedback, and reduced-motion fallbacks.','/animate Add restrained motion to the product story and navigation.'],
  ['/document','Planned','Yes','Creates or updates a Google Stitch-compatible DESIGN.md from the implementation and selected direction.','/document Generate DESIGN.md for the current application.'],
  ['/critique','Planned','No','Answers one focused design question using evidence from source, rendered UI, and the established direction.','/critique Why does the homepage hero feel visually weak?'],
  ['/responsive','Planned','Yes','Repairs overflow, wrapping, navigation, touch targets, content order, density, and breakpoint-specific composition.','/responsive Repair the pricing route from 320px through desktop.'],
  ['/accessibility','Planned','Optional','Audits and optionally repairs semantics, keyboard use, focus, labels, contrast, touch targets, and motion preferences.','/accessibility Audit checkout, then fix high-severity findings.'],
  ['/typography','Planned','Yes','Refines font loading, scale, hierarchy, line length, weight, rhythm, and responsive type behavior.','/typography Improve the article hierarchy without changing its voice.'],
  ['/color','Planned','Yes','Improves palette cohesion, semantic roles, contrast, interaction states, and design-token usage.','/color Normalize semantic colors and repair contrast failures.'],
  ['/layout','Planned','Yes','Improves composition, alignment, whitespace, section pacing, density, and hierarchy without a full redesign.','/layout Give the features route a clearer reading path.'],
  ['/states','Planned','Yes','Completes hover, focus, active, selected, disabled, loading, empty, error, success, and skeleton states.','/states Complete all states for account settings.'],
  ['/copy','Planned','Yes','Improves interface headings, supporting text, CTA labels, forms, empty states, errors, and confirmations.','/copy Make onboarding clearer while preserving product claims.'],
  ['/assets','Planned','Optional','Audits imagery, icons, and illustrations for quality, consistency, relevance, performance, and accessibility.','/assets Review the landing-page imagery and replace weak assets.'],
  ['/performance','Planned','Optional','Finds user-visible problems in media, fonts, layout stability, animation, rendering, and loading priority.','/performance Measure and repair visual performance regressions.'],
  ['/compare','Planned','No','Compares the implementation with a screenshot, mockup, reference, DESIGN.md, or selected direction.','/compare Compare /pricing with the attached approved mockup.'],
  ['/consistency','Planned','Optional','Detects and optionally repairs design-system drift while preserving intentional variation.','/consistency Find control and spacing drift across the application.'],
  ['/final-pass','Planned','Yes','Orchestrates release-quality visual, responsive, accessibility, state, performance, build, and direction checks.','/final-pass Prepare the marketing site for release.'],
].map(([name,status,mutates,description,example]) => ({ name,status,mutates,description,example } as Command));

const phases = [
  ['01','Discover','start_art_direction ? get_discovery_questions ? submit_discovery_answers','Give Universal the product goal, audience, content, constraints, and page map. Answer only what materially changes the result.'],
  ['02','Approve the brief','get_creative_brief ? revise_creative_brief ? approve_creative_brief','Review assumptions before design begins. Approval is digest-bound, so revised decisions invalidate stale downstream work.'],
  ['03','Select a direction','develop_art_direction ? get_selected_direction','Develop differentiated concepts, inspect their rationale, then bind the recommended direction to the approved brief.'],
  ['04','Plan and build','create_design_plan_v2 ? prepare_react_generation ? build_react_project','Compile a versioned visual contract, prepare the generation context, and submit authored React source to the trusted runtime.'],
  ['05','Review and refine','review_implementation','Submit React and CSS with desktop and mobile evidence. Fix material findings and review again.'],
];
const firstPrompt = `Use Universal for a new React product site.\n\nStart with discovery and keep the latest serialized session.\nAsk me before approving the creative brief.\nUse Design Plan v2 and preserve its protected invariants.\nBuild, inspect desktop and mobile, then review the implementation.`;

function Section({ number,label,title,id,children }: { number:string; label:string; title:string; id:string; children:React.ReactNode }) {
  return <section className="docs-section" id={id}><div className="docs-section-heading"><span>{number}</span><div><p className="section-label">{label}</p><h2>{title}</h2></div></div><div className="docs-prose">{children}</div></section>;
}
function Tools({ title,tools }: { title:string; tools:string[] }) { return <div><h3>{title}</h3><p>{tools.map(tool => <code key={tool}>{tool}</code>)}</p></div>; }

export function DocsPage() {
  const [query,setQuery] = useState('');
  const filtered = commands.filter(command => `${command.name} ${command.description}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <><a className="skip-link" href="#docs-content">Skip to documentation</a><Navigation /><main className="docs-page" id="docs-content">
    <header className="docs-hero" id="overview"><p className="section-label">Universal / Field manual</p><p className="docs-edition">Edition 01<br />MCP + agent skills</p><h1><span>Design with</span><span>direction.</span><em>Return with proof.</em></h1><p className="docs-deck">A practical reference for taking Universal from first prompt to reviewed React implementation&mdash;and choosing the right command when an interface needs another pass.</p><div className="docs-hero-links"><a href="#quick-start">Start in five minutes <span>?</span></a><a href="#commands">Browse commands <span>?</span></a></div></header>
    <div className="docs-shell"><aside className="docs-index" aria-label="Documentation chapters"><p>On this page</p><nav><a href="#quick-start"><span>01</span>Quick start</a><a href="#workflow"><span>02</span>MCP workflow</a><a href="#commands"><span>03</span>Commands</a><a href="#power-use"><span>04</span>Power use</a><a href="#reference"><span>05</span>Reference</a></nav><a className="docs-index-install" href="/install">Installation ?</a></aside><div className="docs-content">
      <Section number="01" label="Quick start" title="Your first directed build." id="quick-start"><p className="docs-lede">Install the MCP, give your agent a concrete product brief, and let Universal hold the design decisions together from discovery through review.</p><ol className="docs-checklist"><li><span>01</span><div><strong>Install Universal.</strong><p>Register the local stdio server with your coding agent.</p></div></li><li><span>02</span><div><strong>Ask for the full workflow.</strong><p>Name the product, audience, pages, constraints, and success criteria.</p></div></li><li><span>03</span><div><strong>Approve deliberately.</strong><p>Read the creative brief and correct assumptions before approving it.</p></div></li><li><span>04</span><div><strong>Review with evidence.</strong><p>Include source plus desktop and mobile observations.</p></div></li></ol><CopyBlock label="A strong first prompt" value={firstPrompt} /><p className="docs-callout"><strong>Keep the session intact.</strong> Every Phase 2 response contains the serialized session required by the next operation. Pass the latest returned session forward and never edit it manually.</p></Section>
      <Section number="02" label="Full MCP workflow" title="Use the gates. Keep the provenance." id="workflow"><p className="docs-lede">Phase 2 makes assumptions inspectable, binds approval to the exact brief, and prevents stale plans from crossing phase boundaries.</p><div className="mcp-phases">{phases.map(([number,title,tools,copy]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><code>{tools}</code><p>{copy}</p></div></article>)}</div><div className="docs-two-up"><div><h3>Use Phase 2 when</h3><p>You need discovery, approval, provenance, generation, and review for a new or substantially redesigned interface.</p></div><div><h3>Use compatibility tools when</h3><p>You need a lower-level plan or focused policy query. <code>create_design_plan</code> does not create a resumable session.</p></div></div></Section>
      <Section number="03" label="Agent skills" title="One command. One clear scope." id="commands"><div className="command-toolbar"><label htmlFor="command-search">Find a command</label><input id="command-search" type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder="Try typography, mobile, review?" /><span>{filtered.length} / {commands.length}</span></div><p className="command-status-note"><strong>Available</strong> commands exist in this repository today. <strong>Planned</strong> commands describe the expanded touch-up surface and are not yet shipped.</p><div className="command-list">{filtered.map((command,index) => <article key={command.name}><div className="command-name"><span>{String(index+1).padStart(2,'0')}</span><h3><code>{command.name}</code></h3></div><div className="command-detail"><div className="command-meta"><span data-status={command.status.toLowerCase()}>{command.status}</span><span>Changes files: {command.mutates}</span></div><p>{command.description}</p><CopyBlock label="Example" value={command.example} /></div></article>)}</div>{!filtered.length && <p className="docs-empty">No command matches ?{query}?. Try motion, copy, mobile, or review.</p>}</Section>
      <Section number="04" label="Power use" title="Get more from the MCP." id="power-use"><div className="power-rules">{[['Use stable request IDs','Reuse an ID only for the same mutating operation and payload. A changed payload returns a conflict.'],['Supply a page map','Define every route?s goal, message, content, actions, navigation relationship, and unique responsibility.'],['Carry the latest session','Return to the last trusted session after a failure; never patch digest-bound session JSON.'],['Protect invariants','Treat composition, navigation, responsive behavior, and protected plan decisions as an implementation contract.'],['Bring visual evidence','Record desktop and mobile screenshots plus observations about clipping, empty regions, media, and controls.'],['Re-review changes','Run the build and checks after repairs, then submit changed source and updated evidence again.']].map(([title,copy],index) => <article key={title}><span>{String(index+1).padStart(2,'0')}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></Section>
      <Section number="05" label="Reference" title="The complete tool surface." id="reference"><div className="tool-reference"><Tools title="Art direction" tools={['start_art_direction','get_discovery_questions','submit_discovery_answers','get_creative_brief','revise_creative_brief','approve_creative_brief','develop_art_direction','get_selected_direction','create_design_plan_v2','get_art_direction_session']} /><Tools title="Generation" tools={['prepare_react_generation','build_react_project']} /><Tools title="Intelligence + review" tools={['create_design_plan','get_design_rules','get_taste_profile','review_implementation']} /></div><div className="docs-next"><p className="section-label">Continue reading</p><h3>Need exact request schemas and error codes?</h3><a href="https://github.com/7shep/universal/blob/main/docs/MCP_REFERENCE.md">Open the MCP reference <span>?</span></a></div></Section>
    </div></div><footer className="docs-footer"><a href="/"><Wordmark /></a><p>Direction before decoration.<br />Evidence before approval.</p><a href="#overview">Back to top ?</a></footer>
  </main></>;
}
